version: '3'
services:
  db:
    image: postgres:12-alpine
    container_name: db
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
      - TZ=Europe/Berlin
      - PGTZ=Europe/Berlin
    command: ["-c", "shared_buffers=256MB", "-c", "max_connections=200"]
    volumes:
      # recreating container and starting reinits the db with files in this dir
      # - ./database/init:/docker-entrypoint-initdb.d
      # use external volume to persist the db state
      - ./volumes/db-data:/var/lib/postgresql/data
    ports:
      - $POSTGRES_PORT_EXT:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - $ADMINER_PORT_EXT:8080
    depends_on:
      - db

  bmbf-foekat:
    build:
      context: .
      dockerfile: foekat.Dockerfile
      args:
        - CRON_TIME_FOEKAT=$CRON_TIME_FOEKAT
    env_file:
      - .env
    container_name: bmbf-foekat
    profiles:
      - cron
    volumes:
      # use external volume to persist the downloaded csv files
      - ./volumes/csv-files:/opt/app/bmbf-foekat/csv-files
      - type: bind
        source: ./.env
        target: /opt/app/bmbf-foekat/.env
    command: ["cron", "-f"]
